### ISSUE TITLE
Questions about the archives

### ISSUE THREAD

**Issue by LucasAssis00** [PSUCyberSecurityLab/AIforCybersecurity#6]
Hello, could you clear me up some doubts?

- I am trying to run the files from chapter 6, but I don't know the exact order it should be executed. Is it indicated somethere I haven't found?

- The database for at least the viruses is gotten from the virusshare website. I've downloaded three of the most recent files to test what I could run, but how to download a significant amount of data for the tests? Also, the ones I've got came as zip files, is it the correct way to run in the python code? Moreover, what kind of files should I use for the benign ones? (I've downloaded some random images , zipped and run them into the binary2image and binary2seq and it appeared all right)

- The readme indicates to run the binary2cfg firstly, but it didn't work in the "if __name__ == '__main__':" part, indicating that "No such file or directory: 'checked'", this occurs again with the other transformations

- Trying to run each zip file isolated with the "createGreyScaleImage()" or "get_sequence()" I've got some files as it was indicated, but I can't proceed with just it, so which is the next step?

- With the images, strangely the virus files were already put in the malware folder, and the random zip files were put in the benign folder. How is it determined without the train/test? Unziped files were always put in the benign folder, even the viruses ones

**Comment by Moirai7** [comment]
1. You may refer to the readme file. First extract CFG and convert bianries to images and seqs. Next, modify the configuration based on your dataset as mentioned. Finally, train and test the model.

2. You may need to unzip the file to get executable files. I guess there will be lots of malware in those zip files and I would suggest you to retreive enough benign samples so that the dataset could be balanced. To test the network, you could use a small dataset first say 500 benign and 500 malicious samples. It would be better if the benign samples are from the same architecture as the malware. For example, both of them are 32 bit windows/linux.

3. I have removed the checked file. You may pull those new commits.

4. please refer to Q1 and Q2

5. Make sure you have put the dataset in the right path as I mentioned in the readme. Or you could change those pathes by yourself.
Take the CFG extraction as an example.
You could modify [here](https://github.com/PSUCyberSecurityLab/AIforCybersecurity/blob/81e43f7d2c2c2578ebc4a6a66bfc585cded4dc2d/Chapter6-Malware-Classification/binary2cfg.py#L106) to get the binaries.  And as shown in function [save](https://github.com/PSUCyberSecurityLab/AIforCybersecurity/blob/81e43f7d2c2c2578ebc4a6a66bfc585cded4dc2d/Chapter6-Malware-Classification/binary2cfg.py#L87), the data will be saved under CFG_features and CFG_hex.

**Comment by LucasAssis00** [comment]
Now the codes run as expected, but regarding the samples of malicious and benign files, could you give me some examples or say where could I find them? Unzipping the VirusShare files gave me html, xhtml and text files, from which I couldn't find a way to obtain the binary ones.

**Comment by LucasAssis00** [comment]
Does this book use a page with the binary files for this chapter's code? My main OS is linux, so I am trying to run on it.

Also, running the binary2image, tf_utils and text_iterators (I've only tested untill this one), it resulted in a warning saying 'Could not find TensorRT'. The readme instructs to run tf_utils after the binary2image, but switching the order still couldn't give an appropriate output. Do you know what could it be?

**Comment by Moirai7** [comment]
> Now the codes run as expected, but regarding the samples of malicious and benign files, could you give me some examples or say where could I find them? Unzipping the VirusShare files gave me html, xhtml and text files, from which I couldn't find a way to obtain the binary ones.

sorry we could not spread malware. You could use windows executable file or linux elf file. To collect benign sample, you could directly download windows executable file from official website.

**Comment by Moirai7** [comment]
> Does this book use a page with the binary files for this chapter's code? My main OS is linux, so I am trying to run on it.
> 
> Also, running the binary2image, tf_utils and text_iterators (I've only tested untill this one), it resulted in a warning saying 'Could not find TensorRT'. The readme instructs to run tf_utils after the binary2image, but switching the order still couldn't give an appropriate output. Do you know what could it be?

You donot have to run text_iterator. What is the error message when you run tf_utils? Also, you need to install tensorflow to run the DL models.
